CREATE TABLE IF NOT EXISTS news (
    id TEXT PRIMARY KEY,
    thumbnail TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(63) NOT NULL,
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
